// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhaseOne.Data;

#nullable disable

namespace PhaseOne.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Enrollment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("AdditionalPoints")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int?>("ExamPoints")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FinishDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Grade")
                        .HasColumnType("int");

                    b.Property<int?>("ProjectPoints")
                        .HasColumnType("int");

                    b.Property<string>("ProjectUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Semester")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("SeminalPoints")
                        .HasColumnType("int");

                    b.Property<string>("SeminalUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint");

                    b.Property<int?>("Year")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("CourseId", "StudentId")
                        .IsUnique();

                    b.ToTable("Enrollments");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AdditionalPoints = 5,
                            CourseId = 1,
                            ExamPoints = 50,
                            FinishDate = new DateTime(2023, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = 10,
                            ProjectPoints = 20,
                            ProjectUrl = "http://example.com/project1",
                            Semester = "winter",
                            SeminalPoints = 20,
                            SeminalUrl = "http://example.com/seminal1",
                            StudentId = 1L,
                            Year = 2022
                        },
                        new
                        {
                            Id = 2L,
                            AdditionalPoints = 0,
                            CourseId = 2,
                            ExamPoints = 45,
                            FinishDate = new DateTime(2024, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = 9,
                            ProjectPoints = 25,
                            ProjectUrl = "http://example.com/project2",
                            Semester = "winter",
                            SeminalPoints = 15,
                            SeminalUrl = "http://example.com/seminal2",
                            StudentId = 2L,
                            Year = 2023
                        },
                        new
                        {
                            Id = 3L,
                            AdditionalPoints = 0,
                            CourseId = 3,
                            ExamPoints = 40,
                            FinishDate = new DateTime(2024, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = 8,
                            ProjectPoints = 20,
                            ProjectUrl = "http://example.com/project3",
                            Semester = "summer",
                            SeminalPoints = 20,
                            SeminalUrl = "http://example.com/seminal3",
                            StudentId = 3L,
                            Year = 2023
                        },
                        new
                        {
                            Id = 4L,
                            AdditionalPoints = 5,
                            CourseId = 4,
                            ExamPoints = 35,
                            FinishDate = new DateTime(2022, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = 7,
                            ProjectPoints = 15,
                            ProjectUrl = "http://example.com/project4",
                            Semester = "summer",
                            SeminalPoints = 15,
                            SeminalUrl = "http://example.com/seminal4",
                            StudentId = 4L,
                            Year = 2021
                        },
                        new
                        {
                            Id = 5L,
                            AdditionalPoints = 10,
                            CourseId = 5,
                            ExamPoints = 50,
                            FinishDate = new DateTime(2023, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = 10,
                            ProjectPoints = 20,
                            ProjectUrl = "http://example.com/project5",
                            Semester = "winter",
                            SeminalPoints = 20,
                            SeminalUrl = "http://example.com/seminal5",
                            StudentId = 5L,
                            Year = 2022
                        },
                        new
                        {
                            Id = 6L,
                            AdditionalPoints = 5,
                            CourseId = 6,
                            ExamPoints = 45,
                            FinishDate = new DateTime(2024, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = 9,
                            ProjectPoints = 25,
                            ProjectUrl = "http://example.com/project6",
                            Semester = "summer",
                            SeminalPoints = 15,
                            SeminalUrl = "http://example.com/seminal6",
                            StudentId = 6L,
                            Year = 2023
                        },
                        new
                        {
                            Id = 7L,
                            AdditionalPoints = 0,
                            CourseId = 7,
                            ExamPoints = 40,
                            FinishDate = new DateTime(2025, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = 8,
                            ProjectPoints = 20,
                            ProjectUrl = "http://example.com/project7",
                            Semester = "winter",
                            SeminalPoints = 20,
                            SeminalUrl = "http://example.com/seminal7",
                            StudentId = 7L,
                            Year = 2024
                        });
                });

            modelBuilder.Entity("PhaseOne.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<string>("EducationLevel")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int?>("FirstTeacherId")
                        .HasColumnType("int");

                    b.Property<string>("Programme")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("SecondTeacherId")
                        .HasColumnType("int");

                    b.Property<int>("Semester")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("FirstTeacherId");

                    b.HasIndex("SecondTeacherId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Credits = 6,
                            EducationLevel = "Bachelor",
                            FirstTeacherId = 1,
                            Programme = "Computer Science",
                            SecondTeacherId = 2,
                            Semester = 1,
                            Title = "Programming 1"
                        },
                        new
                        {
                            Id = 2,
                            Credits = 6,
                            EducationLevel = "Bachelor",
                            FirstTeacherId = 2,
                            Programme = "Software Engineering",
                            SecondTeacherId = 3,
                            Semester = 3,
                            Title = "Databases"
                        },
                        new
                        {
                            Id = 3,
                            Credits = 6,
                            EducationLevel = "Bachelor",
                            FirstTeacherId = 3,
                            Programme = "Computer Science",
                            SecondTeacherId = 4,
                            Semester = 5,
                            Title = "Algorithms"
                        },
                        new
                        {
                            Id = 4,
                            Credits = 6,
                            EducationLevel = "Bachelor",
                            FirstTeacherId = 4,
                            Programme = "Software Engineering",
                            SecondTeacherId = 5,
                            Semester = 4,
                            Title = "Web Development"
                        },
                        new
                        {
                            Id = 5,
                            Credits = 6,
                            EducationLevel = "Bachelor",
                            FirstTeacherId = 5,
                            Programme = "Computer Science",
                            SecondTeacherId = 6,
                            Semester = 6,
                            Title = "Operating Systems"
                        },
                        new
                        {
                            Id = 6,
                            Credits = 6,
                            EducationLevel = "Bachelor",
                            FirstTeacherId = 6,
                            Programme = "Computer Science",
                            SecondTeacherId = 7,
                            Semester = 7,
                            Title = "Networks"
                        },
                        new
                        {
                            Id = 7,
                            Credits = 6,
                            EducationLevel = "Bachelor",
                            FirstTeacherId = 7,
                            Programme = "Software Engineering",
                            SecondTeacherId = 1,
                            Semester = 8,
                            Title = "Software Engineering"
                        });
                });

            modelBuilder.Entity("PhaseOne.Models.SeminarWork", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("SeminarWork");
                });

            modelBuilder.Entity("PhaseOne.Models.Student", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("AcquiredCredits")
                        .HasColumnType("int");

                    b.Property<int?>("CurrentSemestar")
                        .HasColumnType("int");

                    b.Property<string>("EducationLevel")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProfileImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AcquiredCredits = 60,
                            CurrentSemestar = 3,
                            EducationLevel = "Bachelor",
                            EnrollmentDate = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Elena",
                            LastName = "Kostova",
                            StudentId = "2025001"
                        },
                        new
                        {
                            Id = 2L,
                            AcquiredCredits = 120,
                            CurrentSemestar = 5,
                            EducationLevel = "Bachelor",
                            EnrollmentDate = new DateTime(2021, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ivan",
                            LastName = "Nikolov",
                            StudentId = "2025002"
                        },
                        new
                        {
                            Id = 3L,
                            AcquiredCredits = 30,
                            CurrentSemestar = 2,
                            EducationLevel = "Bachelor",
                            EnrollmentDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Marija",
                            LastName = "Stojanova",
                            StudentId = "2025003"
                        },
                        new
                        {
                            Id = 4L,
                            AcquiredCredits = 180,
                            CurrentSemestar = 7,
                            EducationLevel = "Bachelor",
                            EnrollmentDate = new DateTime(2020, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Petar",
                            LastName = "Iliev",
                            StudentId = "2025004"
                        },
                        new
                        {
                            Id = 5L,
                            AcquiredCredits = 90,
                            CurrentSemestar = 4,
                            EducationLevel = "Bachelor",
                            EnrollmentDate = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Simona",
                            LastName = "Georgieva",
                            StudentId = "2025005"
                        },
                        new
                        {
                            Id = 6L,
                            AcquiredCredits = 150,
                            CurrentSemestar = 6,
                            EducationLevel = "Bachelor",
                            EnrollmentDate = new DateTime(2021, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Aleksandar",
                            LastName = "Trajkovski",
                            StudentId = "2025006"
                        },
                        new
                        {
                            Id = 7L,
                            AcquiredCredits = 15,
                            CurrentSemestar = 1,
                            EducationLevel = "Bachelor",
                            EnrollmentDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Sara",
                            LastName = "Mitreva",
                            StudentId = "2025007"
                        });
                });

            modelBuilder.Entity("Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AcademicRank")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Degree")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OfficeNumber")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ProfileImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AcademicRank = "Professor",
                            Degree = "PhD",
                            FirstName = "Lila",
                            HireDate = new DateTime(2015, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Petrova",
                            OfficeNumber = "101"
                        },
                        new
                        {
                            Id = 2,
                            AcademicRank = "Assistant",
                            Degree = "MSc",
                            FirstName = "Marko",
                            HireDate = new DateTime(2018, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Stojanovski",
                            OfficeNumber = "102"
                        },
                        new
                        {
                            Id = 3,
                            AcademicRank = "Associate Professor",
                            Degree = "PhD",
                            FirstName = "Ivana",
                            HireDate = new DateTime(2016, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Koleva",
                            OfficeNumber = "103"
                        },
                        new
                        {
                            Id = 4,
                            AcademicRank = "Assistant",
                            Degree = "MSc",
                            FirstName = "Stefan",
                            HireDate = new DateTime(2019, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Jovanov",
                            OfficeNumber = "104"
                        },
                        new
                        {
                            Id = 5,
                            AcademicRank = "Professor",
                            Degree = "PhD",
                            FirstName = "Biljana",
                            HireDate = new DateTime(2014, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Ristova",
                            OfficeNumber = "105"
                        },
                        new
                        {
                            Id = 6,
                            AcademicRank = "Assistant",
                            Degree = "MSc",
                            FirstName = "Miki",
                            HireDate = new DateTime(2020, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Todorov",
                            OfficeNumber = "106"
                        },
                        new
                        {
                            Id = 7,
                            AcademicRank = "Associate Professor",
                            Degree = "PhD",
                            FirstName = "Dragana",
                            HireDate = new DateTime(2017, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Spasova",
                            OfficeNumber = "107"
                        });
                });

            modelBuilder.Entity("Enrollment", b =>
                {
                    b.HasOne("PhaseOne.Models.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhaseOne.Models.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("PhaseOne.Models.Course", b =>
                {
                    b.HasOne("Teacher", "FirstTeacher")
                        .WithMany("FirstTeacherCourses")
                        .HasForeignKey("FirstTeacherId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Teacher", "SecondTeacher")
                        .WithMany("SecondTeacherCourses")
                        .HasForeignKey("SecondTeacherId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("FirstTeacher");

                    b.Navigation("SecondTeacher");
                });

            modelBuilder.Entity("PhaseOne.Models.SeminarWork", b =>
                {
                    b.HasOne("PhaseOne.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhaseOne.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("PhaseOne.Models.Course", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("PhaseOne.Models.Student", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("Teacher", b =>
                {
                    b.Navigation("FirstTeacherCourses");

                    b.Navigation("SecondTeacherCourses");
                });
#pragma warning restore 612, 618
        }
    }
}
